### ISSUE TITLE
Creation failure - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by kwilson** [palmerhq/tsdx#56]
### Current Behavior

When running `npx tsdx create mylib`, the installation fails with the error:

```
√ Created mylib
× Failed to install dependencies
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

    at assertPath (path.js:39:11)
    at Object.normalize (path.js:285:5)
    at parseNonShell (C:\Users\kevin\AppData\Roaming\npm-cache\_npx\12552\node_modules\tsdx\node_modules\execa\node_modules\cross-spawn\lib\parse.js:54:31)
    at Function.parse [as _parse] (C:\Users\kevin\AppData\Roaming\npm-cache\_npx\12552\node_modules\tsdx\node_modules\execa\node_modules\cross-spawn\lib\parse.js:122:49)
    at handleArgs (C:\Users\kevin\AppData\Roaming\npm-cache\_npx\12552\node_modules\tsdx\node_modules\execa\index.js:41:23)
    at Object.module.exports [as default] (C:\Users\kevin\AppData\Roaming\npm-cache\_npx\12552\node_modules\tsdx\node_modules\execa\index.js:199:17)
    at prog.version.command.describe.action (C:\Users\kevin\AppData\Roaming\npm-cache\_npx\12552\node_modules\tsdx\dist\index.js:172:30)
```

### Expected behavior

Should successfully generate the full template, install deps, etc.

### Additional context

I tried poking around in the code and can see that it's failing on

```
await execa(getInstallArgs(getInstallCmd(), deps));
```

As far as I can tell, it's trying to run via yarn on my machine.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |0.5.0
| TypeScript       |
| Browser          |
| npm/Yarn         |6.4.1/1.13.0
| Operating System |Windows 10 Pro (1809)

**Comment by kwilson** [comment]
Haha, so 0.5.1 was published while I was writing that up and all working now.
